name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: python -m pip install uv
      - name: Verify lock file
        run: |
          bash bootstrap_env.sh
          git diff --exit-code requirements.lock
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
